# config/services.yaml

parameters:
    huggingface_api_key: '%env(HUGGINGFACE_API_KEY)%'
    huggingface_model: 'mistralai/Mistral-7B-Instruct-v0.2'

    uploads_directory: '%kernel.project_dir%/public/uploads/events'
    app.mailer_from: '%env(MAILER_FROM)%'
    app.notification_email: '%env(APP_NOTIFICATION_EMAIL)%'
    app.publicite_notification_email: '%env(APP_PUBLICITE_NOTIFICATION_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CloudinaryUploader:
        arguments:
            $cloudinaryUrl: '%env(CLOUDINARY_URL)%'

    App\Service\AiDescriptionService:
        arguments:
            $huggingfaceApiKey: '%huggingface_api_key%'
            $huggingfaceModel: '%huggingface_model%'
